Testing Git

In [8]:
import pandas as pd
df = pd.read_csv("Email Data.csv")
df

,Sent Date,Subject Line,Category 1,Category 2,Campus,Type,Total Sent,Total Opens,Unique Opens,Not Opened,...,Unnamed: 1015,Unnamed: 1016,Unnamed: 1017,Unnamed: 1018,Unnamed: 1019,Unnamed: 1020,Unnamed: 1021,Unnamed: 1022,Unnamed: 1023,Unnamed: 1024
0,1/4/17,USFSCO SMMC January E-Newsletter,ENEWSLETTER,MONTHLY,ALL,PARENT,1103,1025.0,501.0,602.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/4/17,USFSCO SMMC January E-Newsletter,ENEWSLETTER,MONTHLY,ALL,EMPLOYEE,72,56.0,26.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/4/17,Savvy Spending Challenge - SMMC's January Enew...,ENEWSLETTER,MONTHLY,ALL,STUDENT,1592,720.0,483.0,1109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2/1/17,6+ Saving Challenges - SMMC's February E-newsl...,ENEWSLETTER,MONTHLY,ALL,STUDENT,1595,668.0,461.0,1134.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2/1/17,6+ Saving Challenges - SMMC's February E-newsl...,ENEWSLETTER,MONTHLY,ALL,EMPLOYEE,76,34.0,22.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
new_df = df["Total Opens"] / df["Unique Opens"]
new_df

0      2.045908
1      2.153846
2      1.490683
3      1.449024
4      1.545455
         ...
336         NaN
337         NaN
338         NaN
339         NaN
340         NaN
Length: 341, dtype: float64